using System.Globalization;
using System.Text.RegularExpressions;
using ShotAI.Core.Json;

namespace ShotAI.Core.Model;

/// <summary>
/// The generated project title and its detector (<c>src/main/project-store.ts:278-293</c>,
/// spec 01 7.2.3). Kept together because a detector that drifts from its generator silently
/// stops matching.
/// </summary>
public static partial class ProjectTitles
{
    /// <summary>
    /// <c>defaultTitle</c>: <c>Project yyyy/MM/dd HH:mm:ss</c> in <paramref name="local"/> time.
    /// The slashes are literal, never the culture's date separator.
    /// </summary>
    public static string DefaultTitle(DateTimeOffset now, TimeZoneInfo local)
    {
        ArgumentNullException.ThrowIfNull(local);
        var t = TimeZoneInfo.ConvertTime(now, local);
        return "Project " + t.ToString("yyyy'/'MM'/'dd HH':'mm':'ss", CultureInfo.InvariantCulture);
    }

    /// <summary>
    /// <c>isAutoGeneratedTitle</c>: true for a title this app generated, and for one that is
    /// empty after <see cref="JsString.Trim"/> (there is nothing to preserve).
    /// </summary>
    public static bool IsAutoGenerated(string title)
    {
        ArgumentNullException.ThrowIfNull(title);
        var t = JsString.Trim(title);
        return t.Length == 0 || AutoTitlePattern().IsMatch(t);
    }

    // [0-9], because JavaScript's \d is ASCII-only, and \z, because .NET's $ also matches before
    // a final newline (EDGE-MODEL-55, D-26).
    [GeneratedRegex(@"^Project [0-9]{4}/[0-9]{2}/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\z", RegexOptions.CultureInvariant)]
    internal static partial Regex AutoTitlePattern();
}
