using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Unicode;

namespace ShotAI.GenBrand;

/// <summary>
/// Turns <c>contract/brand.json</c> into the C# brand table,
/// <c>src/ShotAI.Core/Brand/BrandPalette.Generated.cs</c> (spec 10 7.2 and 7.3).
/// </summary>
/// <remarks>
/// The rules, their order and their messages are those of <c>scripts/gen-brand.mjs</c>
/// (spec 10 2.2), so the Windows builds cannot read the contract two ways. Where the
/// JavaScript emits garbage or crashes, this fails with a message instead (the IMPROVEMENT
/// rows of spec 10 7.3). Every value that becomes code is either a checked name or an
/// escaped literal: nothing in the contract can inject C#.
/// </remarks>
public static class BrandGenerator
{
    /// <summary>Where the generated table lives, relative to the repository root.</summary>
    public const string OutputRelativePath = "dotnet/src/ShotAI.Core/Brand/BrandPalette.Generated.cs";

    // The emitted brands, in BRAND_IDS order, and their C# field names. A third contract
    // brand is ignored, as in gen-brand.mjs.
    private static readonly (string Id, string Field)[] Brands = [("shotAI", "ShotAI"), ("lfi", "Lfi")];

    private static readonly string[] RadiusKeys = ["panel", "card", "figure", "control", "controlSm", "micro", "chip"];

    private static readonly string[] Modes = ["light", "dark"];

    private static ReadOnlySpan<byte> Utf8Bom => [0xEF, 0xBB, 0xBF];

    /// <summary>
    /// The contract stamp: SHA-256 of the bytes with every CR LF replaced by LF, in lowercase
    /// hex. A CRLF checkout hashes the same as the LF file (EDGE-INFRA-1).
    /// </summary>
    /// <exception cref="GenBrandException">The bytes are not valid UTF-8.</exception>
    public static string ContractHash(ReadOnlySpan<byte> contractBytes)
    {
        if (!Utf8.IsValid(contractBytes)) throw new GenBrandException("contract/brand.json is not valid UTF-8");
        var canonical = new byte[contractBytes.Length];
        var n = 0;
        for (var i = 0; i < contractBytes.Length; i++)
        {
            if (contractBytes[i] == 0x0D && i + 1 < contractBytes.Length && contractBytes[i + 1] == 0x0A) continue;
            canonical[n++] = contractBytes[i];
        }
        return Convert.ToHexStringLower(SHA256.HashData(canonical.AsSpan(0, n)));
    }

    /// <summary>The whole generated file: LF line endings, ending with one newline.</summary>
    /// <exception cref="GenBrandException">The contract cannot be generated.</exception>
    public static string Generate(ReadOnlySpan<byte> contractBytes)
    {
        var hash = ContractHash(contractBytes);
        using var doc = Parse(contractBytes);
        var spec = doc.RootElement;

        var tokens = Tokens(spec);
        var renames = Prop(spec, "windowsRenames");
        if (Prop(spec, "brands") is not { ValueKind: JsonValueKind.Object } brands)
            throw new GenBrandException("spec has no brands");

        // Before any emission or colour validation, and for every brand in the contract.
        CheckInvariants(spec, brands);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("// GENERATED by dotnet/tools/ShotAI.GenBrand from contract/brand.json. DO NOT EDIT.\n");
        sb.Append("// contract sha256: ").Append(hash).Append('\n');
        sb.Append("//\n");
        sb.Append("// Change a colour in contract/brand.json and regenerate. The same file drives\n");
        sb.Append("// src/shared/brand-colors.generated.ts here and BrandPalette+Generated.swift in\n");
        sb.Append("// Armadillon44/shotAI_MacOS, so the platforms cannot disagree about a value\n");
        sb.Append("// none of them owns. Everything about how these are consumed lives in\n");
        sb.Append("// BrandPalette.cs, by hand. Only the table is generated.\n");
        sb.Append("namespace ShotAI.Core.Brand;\n");
        sb.Append('\n');
        sb.Append("public static partial class BrandPalette\n");
        sb.Append("{\n");
        foreach (var (id, field) in Brands)
        {
            EmitBrand(sb, brands, id, field, tokens, renames);
            sb.Append('\n');
        }
        sb.Append("    public static IReadOnlyList<BrandDefinition> All { get; } = [")
          .Append(string.Join(", ", Brands.Select(b => b.Field)))
          .Append("];\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static JsonDocument Parse(ReadOnlySpan<byte> bytes)
    {
        // Node's JSON.parse fails on the U+FEFF a BOM decodes to, so this is parity in outcome.
        if (bytes.StartsWith(Utf8Bom))
            throw new GenBrandException("cannot parse contract/brand.json: it starts with a UTF-8 byte order mark");
        try
        {
            return JsonDocument.Parse(bytes.ToArray());
        }
        catch (JsonException e)
        {
            throw new GenBrandException("cannot parse contract/brand.json: " + e.Message);
        }
    }

    private static List<string> Tokens(JsonElement spec)
    {
        const string missing = "spec has no platforms.windows.colors";
        if (Prop(Prop(Prop(spec, "platforms"), "windows"), "colors") is not { ValueKind: JsonValueKind.Array } colors)
            throw new GenBrandException(missing);
        var tokens = new List<string>();
        foreach (var t in colors.EnumerateArray())
        {
            if (t.ValueKind != JsonValueKind.String) throw new GenBrandException(missing);
            var name = t.GetString()!;
            if (!IsName(name)) throw new GenBrandException($"platforms.windows.colors: {Json(t)} is not a token name");
            tokens.Add(name);
        }
        return tokens;
    }

    private static void CheckInvariants(JsonElement spec, JsonElement brands)
    {
        if (Prop(spec, "invariants") is not { ValueKind: JsonValueKind.Array } invariants) return;
        foreach (var inv in invariants.EnumerateArray())
        {
            if (Str(Prop(inv, "rule")) != "distinct") continue;
            if (Prop(inv, "tokens") is not { ValueKind: JsonValueKind.Array } pair || pair.GetArrayLength() != 2) continue;
            var t0 = Str(pair[0]);
            var t1 = Str(pair[1]);
            var mode = Str(Prop(inv, "mode"));
            if (t0 is null || t1 is null || mode is null) continue;

            foreach (var (name, brand) in Entries(brands))
            {
                var x = Str(Prop(Prop(Prop(brand, "colors"), t0), mode));
                var y = Str(Prop(Prop(Prop(brand, "colors"), t1), mode));
                if (x is { Length: > 0 } && y is { Length: > 0 } && string.Equals(x, y, StringComparison.Ordinal))
                {
                    throw new GenBrandException(
                        $"invariant violated \u2014 {name}.{mode}: {t0} and {t1} are both {x}.\n  {Str(Prop(inv, "why")) ?? ""}");
                }
            }
        }
    }

    // Per brand, the first error is Electron's (spec 10 2.2 step 5): brand missing, no radii,
    // no font, then this generator's own checks of the label, the radii and the font, then
    // the colours, light before dark.
    private static void EmitBrand(
        StringBuilder sb, JsonElement brands, string id, string field, List<string> tokens, JsonElement? renames)
    {
        var brand = Prop(brands, id);
        if (IsNullish(brand)) throw new GenBrandException($"brand {id} missing from the contract");
        var radii = Prop(brand, "radii");
        if (IsNullish(radii)) throw new GenBrandException($"{id}: no radii");
        var font = Prop(brand, "font");
        if (IsNullish(font)) throw new GenBrandException($"{id}: no font");

        var label = Str(Prop(brand, "label")) ?? throw new GenBrandException($"{id}: no label");
        var radiusValues = RadiusKeys.Select(k => (Key: k, Value: Radius(id, radii, k))).ToList();
        var family = OptionalString(id, font, "family");
        var postScriptName = OptionalString(id, font, "postScriptName");
        var fallbacks = Fallbacks(id, font);
        var labelStretch = OptionalNumber(id, font, "labelStretch");
        var palettes = Modes.Select(mode => Palette(id, brand, mode, tokens, renames)).ToList();

        sb.Append("    public static readonly BrandDefinition ").Append(field).Append(" = new(\n");
        sb.Append("        Id: ").Append(Lit(id)).Append(",\n");
        sb.Append("        Label: ").Append(Lit(label)).Append(",\n");
        sb.Append("        Radii: new BrandRadii(")
          .Append(string.Join(", ", radiusValues.Select(r => Pascal(r.Key) + ": " + (r.Value is { } v ? Num(v) : "null"))))
          .Append("),\n");
        sb.Append("        Font: new BrandFont(\n");
        sb.Append("            Family: ").Append(family is null ? "null" : Lit(family)).Append(",\n");
        sb.Append("            PostScriptName: ").Append(postScriptName is null ? "null" : Lit(postScriptName)).Append(",\n");
        sb.Append("            Fallbacks: [").Append(string.Join(", ", fallbacks.Select(Lit))).Append("],\n");
        sb.Append("            LabelStretch: ").Append(labelStretch is { } s ? Num(s) : "null").Append("),\n");
        for (var m = 0; m < Modes.Length; m++)
        {
            sb.Append("        ").Append(Pascal(Modes[m])).Append(": new Palette(\n");
            var entries = palettes[m];
            for (var i = 0; i < entries.Count; i++)
            {
                sb.Append("            ").Append(Pascal(entries[i].Role)).Append(": ").Append(Lit(entries[i].Hex))
                  .Append(i < entries.Count - 1 ? ",\n" : m < Modes.Length - 1 ? "),\n" : "));\n");
            }
        }
    }

    // platformValue: an object takes its `windows` member. Only `chip` may be null (a capsule).
    private static double? Radius(string id, JsonElement? radii, string key)
    {
        var value = Prop(radii, key);
        if (value is { ValueKind: JsonValueKind.Object } split)
        {
            value = Prop(split, "windows");
            if (value is null) throw new GenBrandException($"{id}.radii.{key}: no windows value");
        }
        if (IsNullish(value))
        {
            if (key == "chip") return null;
            throw new GenBrandException($"{id}.radii.{key}: must be a number");
        }
        if (value is { ValueKind: JsonValueKind.Number } n && n.TryGetDouble(out var d) && double.IsFinite(d)) return d;
        throw new GenBrandException($"{id}.radii.{key}: must be a number");
    }

    private static string? OptionalString(string id, JsonElement? font, string key)
    {
        var value = Prop(font, key);
        if (IsNullish(value)) return null;
        return Str(value) ?? throw new GenBrandException($"{id}.font.{key}: must be a string or null");
    }

    private static double? OptionalNumber(string id, JsonElement? font, string key)
    {
        var value = Prop(font, key);
        if (IsNullish(value)) return null;
        if (value is { ValueKind: JsonValueKind.Number } n && n.TryGetDouble(out var d) && double.IsFinite(d)) return d;
        throw new GenBrandException($"{id}.font.{key}: must be a number or null");
    }

    private static List<string> Fallbacks(string id, JsonElement? font)
    {
        var value = Prop(font, "fallbacks");
        if (IsNullish(value)) return [];
        if (value is not { ValueKind: JsonValueKind.Array } array || array.EnumerateArray().Any(e => e.ValueKind != JsonValueKind.String))
            throw new GenBrandException($"{id}.font.fallbacks: must be an array of strings");
        return array.EnumerateArray().Select(e => e.GetString()!).ToList();
    }

    private static List<(string Role, string Hex)> Palette(
        string id, JsonElement? brand, string mode, List<string> tokens, JsonElement? renames)
    {
        var entries = new List<(string, string)>(tokens.Count);
        foreach (var t in tokens)
        {
            var colour = Prop(Prop(brand, "colors"), t);
            if (IsNullish(colour)) throw new GenBrandException($"{id}: no colour \"{t}\" in the contract");
            var value = Prop(colour, mode);
            var hex = Str(value);
            if (hex is null || !IsLowerHex(hex))
                throw new GenBrandException($"{id}.{t}.{mode}: expected a lowercase 6-digit #rrggbb, got {Json(value)}");
            entries.Add((Role(t, renames), hex));
        }
        return entries;
    }

    // windowsRenames[t] ?? t, as a checked C# name.
    private static string Role(string token, JsonElement? renames)
    {
        var renamed = Prop(renames, token);
        if (IsNullish(renamed)) return token;
        var role = Str(renamed);
        if (role is null || !IsName(role))
            throw new GenBrandException($"windowsRenames.{token}: {Json(renamed)} is not a role name");
        return role;
    }

    // ^#[0-9a-f]{6}\z, ASCII and lowercase only (INV-INFRA-4).
    private static bool IsLowerHex(string s)
    {
        if (s.Length != 7 || s[0] != '#') return false;
        for (var i = 1; i < 7; i++)
        {
            if (s[i] is not ((>= '0' and <= '9') or (>= 'a' and <= 'f'))) return false;
        }
        return true;
    }

    // A token or role name becomes a C# identifier: ^[a-z][A-Za-z0-9]*\z.
    private static bool IsName(string s)
    {
        if (s.Length == 0 || s[0] is < 'a' or > 'z') return false;
        foreach (var c in s)
        {
            if (c is not ((>= 'a' and <= 'z') or (>= 'A' and <= 'Z') or (>= '0' and <= '9'))) return false;
        }
        return true;
    }

    private static string Pascal(string name) => char.ToUpperInvariant(name[0]) + name[1..];

    // An integer prints without a fraction; anything else is the shortest round-trip form.
    private static string Num(double v) =>
        v == Math.Floor(v) && Math.Abs(v) < 1e15
            ? ((long)v).ToString(CultureInfo.InvariantCulture)
            : v.ToString("R", CultureInfo.InvariantCulture);

    // A C# regular string literal. U+0085, U+2028 and U+2029 are line terminators to the C#
    // compiler, so they are escaped with the control characters.
    private static string Lit(string s)
    {
        var sb = new StringBuilder(s.Length + 2).Append('"');
        foreach (var c in s)
        {
            if (c == '\\') sb.Append("\\\\");
            else if (c == '"') sb.Append("\\\"");
            else if (c < ' ' || c == '\u0085' || c == '\u2028' || c == '\u2029')
                sb.Append("\\u").Append(((int)c).ToString("X4", CultureInfo.InvariantCulture));
            else sb.Append(c);
        }
        return sb.Append('"').ToString();
    }

    // JSON.stringify of a value, for messages; a missing value is `undefined`, as the
    // template literal in gen-brand.mjs prints it.
    private static string Json(JsonElement? value) => value switch
    {
        null => "undefined",
        { ValueKind: JsonValueKind.String } s => Quote(s),
        { ValueKind: JsonValueKind.Number } n => n.TryGetDouble(out var d) && double.IsFinite(d) ? Num(d) : "null",
        { ValueKind: JsonValueKind.True } => "true",
        { ValueKind: JsonValueKind.False } => "false",
        { ValueKind: JsonValueKind.Array } a => "[" + string.Join(",", a.EnumerateArray().Select(e => Json(e))) + "]",
        { ValueKind: JsonValueKind.Object } o =>
            "{" + string.Join(",", Entries(o).Select(p => QuoteText(p.Name) + ":" + Json(p.Value))) + "}",
        _ => "null",
    };

    private static string Quote(JsonElement s)
    {
        try
        {
            return QuoteText(s.GetString()!);
        }
        catch (InvalidOperationException)
        {
            return s.GetRawText();   // an escaped lone surrogate; the raw text is close enough for a message
        }
    }

    private static string QuoteText(string s)
    {
        var sb = new StringBuilder(s.Length + 2).Append('"');
        foreach (var c in s)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\b': sb.Append("\\b"); break;
                case '\f': sb.Append("\\f"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < ' ') sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    else sb.Append(c);
                    break;
            }
        }
        return sb.Append('"').ToString();
    }

    // `??` in JavaScript: a missing member and JSON null are both nullish.
    private static bool IsNullish(JsonElement? e) => e is null || e.Value.ValueKind == JsonValueKind.Null;

    private static string? Str(JsonElement? e) => e is { ValueKind: JsonValueKind.String } s ? s.GetString() : null;

    // obj?.[name]: null unless obj is an object with that member. The last duplicate wins,
    // as in JSON.parse.
    private static JsonElement? Prop(JsonElement? obj, string name)
    {
        if (obj is not { ValueKind: JsonValueKind.Object } o) return null;
        JsonElement? found = null;
        foreach (var p in o.EnumerateObject())
        {
            if (p.NameEquals(name)) found = p.Value;
        }
        return found;
    }

    // Object.entries in document order, a duplicate keeping its first position and last value.
    private static List<(string Name, JsonElement Value)> Entries(JsonElement obj)
    {
        var list = new List<(string Name, JsonElement Value)>();
        var at = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var p in obj.EnumerateObject())
        {
            if (at.TryGetValue(p.Name, out var i)) list[i] = (p.Name, p.Value);
            else
            {
                at[p.Name] = list.Count;
                list.Add((p.Name, p.Value));
            }
        }
        return list;
    }
}
