using ShotAI.Core.Json;
using ShotAI.Core.Model;
using Xunit;

namespace ShotAI.Core.Tests.Codec;

/// <summary>
/// Ported regexes use <c>\z</c> and <c>[0-9]</c> (EDGE-MODEL-55, D-26): .NET's <c>$</c> also
/// matches before a final newline, and its <c>\d</c> matches every Unicode decimal digit.
/// The import whitelist's newline case is <c>Store/CreateFromImportTests</c>: <c>[^/]</c> matches
/// a newline in both engines, so that name passes both whitelists.
/// </summary>
public sealed class RegexAnchorTests
{
    [Fact]
    public void AFinalNewlineFailsTheAutoTitlePatternAndPassesAfterTrim()
    {
        const string title = "Project 2026/01/01 00:00:00\n";
        Assert.DoesNotMatch(ProjectTitles.AutoTitlePattern(), title);
        Assert.Matches(ProjectTitles.AutoTitlePattern(), JsString.Trim(title));
        Assert.True(ProjectTitles.IsAutoGenerated(title));
    }

    /// <summary>Arabic-Indic digits (U+0660 to U+0669) are decimal digits to .NET's <c>\d</c>, not to JavaScript's.</summary>
    [Fact]
    public void NonAsciiDigitsDoNotMatch()
    {
        var digits = Arabic("2026") + "/" + Arabic("01") + "/" + Arabic("01") + " " + Arabic("00") + ":" + Arabic("00") + ":" + Arabic("00");
        Assert.False(ProjectTitles.IsAutoGenerated("Project " + digits));
        Assert.True(ProjectTitles.IsAutoGenerated("Project 2026/01/01 00:00:00"));
    }

    private static string Arabic(string asciiDigits) =>
        new(asciiDigits.Select(c => (char)(0x0660 + (c - '0'))).ToArray());
}
