// Native Microsoft PowerPoint (.pptx) export (D4). One slide per step, good for
// training decks / screen-shares. Built from the same fail-closed ExportItem[] as
// every other exporter, so slides only ever contain the redaction-baked renders.
// Pure-JS `pptxgenjs` (no CDN, no native deps).
import pptxgen from 'pptxgenjs';
import type { CalloutKind, ProjectManifest } from '../shared/project';
import { loadItemImage, type ExportItem } from './export';

// LAYOUT_WIDE = 13.333in × 7.5in. All positions below are in inches.
const SLIDE_W = 13.333;
const SLIDE_H = 7.5;
const MARGIN = 0.5;

const CALLOUT: Record<CalloutKind, { fill: string; fg: string; label: string }> = {
  note: { fill: 'ECFDF5', fg: '065F46', label: 'Note' },
  caution: { fill: 'FFFBEB', fg: '92400E', label: 'Caution' },
  warning: { fill: 'FEF2F2', fg: '991B1B', label: 'Warning' },
};

/** Fit (w×h px) inside the box preserving aspect; return centered inches. */
function fitContain(
  pxW: number,
  pxH: number,
  box: { x: number; y: number; w: number; h: number },
): { x: number; y: number; w: number; h: number } {
  const ar = pxW > 0 && pxH > 0 ? pxW / pxH : 1;
  let w = box.w;
  let h = w / ar;
  if (h > box.h) {
    h = box.h;
    w = h * ar;
  }
  return { x: box.x + (box.w - w) / 2, y: box.y + (box.h - h) / 2, w, h };
}

export async function buildPptx(
  manifest: ProjectManifest,
  items: ExportItem[],
  generatedAt: string,
): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'shotAI';
  pptx.title = manifest.title;

  // Title slide.
  const title = pptx.addSlide();
  title.background = { color: 'FFFFFF' };
  title.addText(manifest.title, {
    x: MARGIN,
    y: manifest.intro && (manifest.intro.heading || manifest.intro.body) ? 2.2 : 3.0,
    w: SLIDE_W - MARGIN * 2,
    h: 1.2,
    fontSize: 40,
    bold: true,
    color: '14161F',
    align: 'center',
  });
  const introBits: string[] = [];
  if (manifest.intro?.heading) introBits.push(manifest.intro.heading);
  if (manifest.intro?.body) introBits.push(manifest.intro.body);
  if (introBits.length) {
    title.addText(introBits.join('\n\n'), {
      x: MARGIN + 1,
      y: 3.6,
      w: SLIDE_W - (MARGIN + 1) * 2,
      h: 2.6,
      fontSize: 16,
      color: '525A6E',
      align: 'center',
      valign: 'top',
    });
  }
  title.addText(`Generated by shotAI · ${generatedAt}`, {
    x: MARGIN,
    y: SLIDE_H - 0.7,
    w: SLIDE_W - MARGIN * 2,
    h: 0.4,
    fontSize: 10,
    color: '8B91A3',
    align: 'center',
  });

  for (const it of items) {
    const slide = pptx.addSlide();
    slide.background = { color: 'FFFFFF' };

    if (it.kind === 'text') {
      if (it.callout) {
        const c = CALLOUT[it.callout];
        slide.addText(
          [
            { text: `${it.heading || c.label}\n`, options: { bold: true, fontSize: 24, color: c.fg } },
            { text: it.body || '', options: { fontSize: 18, color: c.fg } },
          ],
          {
            x: 1.5,
            y: 2.2,
            w: SLIDE_W - 3,
            h: 3.1,
            fill: { color: c.fill },
            align: 'left',
            valign: 'top',
            margin: 16,
          },
        );
        continue;
      }
      // Plain section slide: heading + body.
      slide.addText(it.heading || '', {
        x: MARGIN,
        y: 0.9,
        w: SLIDE_W - MARGIN * 2,
        h: 1,
        fontSize: 28,
        bold: true,
        color: '14161F',
      });
      if (it.body) {
        slide.addText(it.body, {
          x: MARGIN,
          y: 2.0,
          w: SLIDE_W - MARGIN * 2,
          h: SLIDE_H - 2.6,
          fontSize: 18,
          color: '374151',
          valign: 'top',
        });
      }
      continue;
    }

    // Shot slide: caption title, contained image, optional instruction; note → speaker notes.
    slide.addText(`${it.n}. ${it.caption || `Step ${it.n}`}`, {
      x: MARGIN,
      y: 0.3,
      w: SLIDE_W - MARGIN * 2,
      h: 0.7,
      fontSize: 20,
      bold: true,
      color: '14161F',
    });
    const hasBody = !!it.body;
    const box = { x: MARGIN, y: 1.1, w: SLIDE_W - MARGIN * 2, h: (hasBody ? SLIDE_H - 2.9 : SLIDE_H - 1.5) };
    const { buffer, width, height } = await loadItemImage(it);
    const b64 = buffer.toString('base64');
    const fit = fitContain(width, height, box);
    slide.addImage({ data: `data:${it.mediaType};base64,${b64}`, x: fit.x, y: fit.y, w: fit.w, h: fit.h });
    if (hasBody) {
      slide.addText(it.body, {
        x: MARGIN,
        y: SLIDE_H - 1.65,
        w: SLIDE_W - MARGIN * 2,
        h: 1.4,
        fontSize: 15,
        color: '374151',
        valign: 'top',
      });
    }
    if (it.note) slide.addNotes(it.note);
  }

  // write() with nodebuffer returns a Node Buffer in the main process.
  const out = await pptx.write({ outputType: 'nodebuffer' });
  return out as Buffer;
}
