// #79 and #80 — what the SOP request actually tells Claude.
import { describe, it, expect, vi } from 'vitest';
vi.mock('electron', () => ({ shell: { showItemInFolder: () => undefined } }));

import { authorIntro, titleInstruction } from './sop-input';
import { isAutoGeneratedTitle } from './project-store';

const intro = (h: string) => ({ heading: h, body: 'b' });

describe('#79 — which overview is sent', () => {
  /// The case that matters: NOT edited, so manifest.intro is Claude's own text
  /// from the last run. Sending it back under "the author already wrote this"
  /// laundered the model's guess into author intent.
  it('prefers the pre-AI snapshot when the author has NOT edited', () => {
    expect(authorIntro({
      intro: intro('Claude wrote this'),
      sopBackup: { intro: intro('the author wrote this') } as never,
    })?.heading).toBe('the author wrote this');
  });

  it('sends the CURRENT overview once the author HAS edited', () => {
    expect(authorIntro({
      intro: intro('the author just edited this'),
      introEditedByUser: true,
      sopBackup: { intro: intro('stale snapshot') } as never,
    })?.heading).toBe('the author just edited this');
  });

  /// First run: nothing generated yet, so the current intro IS the author's.
  it('uses the current overview when there is no backup', () => {
    expect(authorIntro({ intro: intro('first run') })?.heading).toBe('first run');
  });

  /// A backup whose intro is null means the author never wrote one — so nothing
  /// should be sent, rather than falling through to Claude's text.
  it('sends nothing when the pre-AI overview was empty', () => {
    expect(authorIntro({
      intro: intro('Claude wrote this'),
      sopBackup: { intro: null } as never,
    })).toBeNull();
  });

  it('still treats whitespace-only as absent', () => {
    expect(authorIntro({ intro: { heading: '  ', body: '\n' } })).toBeNull();
  });
});

describe('#80 — isAutoGeneratedTitle matches the generator', () => {
  it.each(['Project 2026/08/19 12:41:16', 'Project 2026/01/01 00:00:00', '', '   '])(
    'detects %s', (t) => expect(isAutoGeneratedTitle(t)).toBe(true),
  );

  it.each([
    'Onboarding a new hire',
    'Project kickoff',                 // starts with the word, not the format
    'Project 2026/8/19 12:41:16',      // unpadded — not what the generator emits
    'Project 2026/08/19',
  ])('leaves %s alone', (t) => expect(isAutoGeneratedTitle(t)).toBe(false));
});

describe('#80 — the title instruction', () => {
  it('orders an auto-generated name replaced', () => {
    const t = titleInstruction('Project 2026/08/19 12:41:16', true);
    expect(t).toContain('generated by the app from a timestamp');
    expect(t).toContain('MUST be replaced');
    expect(t).toContain('Project 2026/08/19 12:41:16'); // the name itself is still sent
  });

  it('treats a human name as intentional', () => {
    const t = titleInstruction('Onboarding a new hire', false);
    expect(t).toContain('written by a person');
    expect(t).not.toContain('MUST be replaced');
  });

  /// NAMES NO FILLER WORDS. Listing them as things to avoid is what put
  /// "placeholder" in the model's mouth on macOS — it obeyed for the title and
  /// wrote it into the `intro` instead, which that sentence never covered.
  it.each(['placeholder', 'untitled', '"SOP"', '"Project"'])(
    'never names the filler word %s', (w) => {
      for (const auto of [true, false]) {
        expect(titleInstruction('X', auto).toLowerCase()).not.toContain(w.toLowerCase());
      }
    },
  );

  it('quotes the name on its own line, away from any word describing it', () => {
    const [first] = titleInstruction('Project 2026/08/19 12:41:16', true).split('\n');
    expect(first).toBe('Current project name: "Project 2026/08/19 12:41:16"');
  });
});
