using System.Globalization;
using ShotAI.Core.Model;
using Xunit;

namespace ShotAI.Core.Tests.Model;

/// <summary>
/// <c>defaultTitle</c> and <c>isAutoGeneratedTitle</c> (spec 01 7.2.3, 2.9.8). The detector
/// cases are the #80 table of spec 07 8.2.
/// </summary>
public sealed class ProjectTitlesTests
{
    private static readonly TimeZoneInfo MinusFive =
        TimeZoneInfo.CreateCustomTimeZone("Test minus five", TimeSpan.FromHours(-5), "Test minus five", "Test minus five");

    [Fact]
    public void TheDefaultTitleIsLocalTimeWithLiteralSlashes()
    {
        var now = new DateTimeOffset(2026, 9, 22, 19, 3, 7, 123, TimeSpan.Zero);
        Assert.Equal("Project 2026/09/22 14:03:07", ProjectTitles.DefaultTitle(now, MinusFive));
        Assert.Equal("Project 2026/09/22 19:03:07", ProjectTitles.DefaultTitle(now, TimeZoneInfo.Utc));
    }

    /// <summary>A culture whose date separator is not "/" changes nothing.</summary>
    [Fact]
    public void TheDefaultTitleIgnoresTheCurrentCulture()
    {
        var saved = CultureInfo.CurrentCulture;
        try
        {
            var dotted = (CultureInfo)CultureInfo.InvariantCulture.Clone();
            dotted.DateTimeFormat.DateSeparator = ".";
            dotted.DateTimeFormat.TimeSeparator = ".";
            CultureInfo.CurrentCulture = dotted;
            var now = new DateTimeOffset(2026, 1, 2, 3, 4, 5, TimeSpan.Zero);
            Assert.Equal("Project 2026/01/02 03:04:05", ProjectTitles.DefaultTitle(now, TimeZoneInfo.Utc));
        }
        finally
        {
            CultureInfo.CurrentCulture = saved;
        }
    }

    [Theory]
    [InlineData("Project 2026/08/19 12:41:16")]
    [InlineData("Project 2026/01/01 00:00:00")]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("  Project 2026/01/01 00:00:00  ")]
    public void AutoGeneratedTitles(string title) => Assert.True(ProjectTitles.IsAutoGenerated(title));

    [Theory]
    [InlineData("Onboarding a new hire")]
    [InlineData("Project kickoff")]
    [InlineData("Project 2026/8/19 12:41:16")]
    [InlineData("Project 2026/08/19")]
    [InlineData("project 2026/08/19 12:41:16")]
    [InlineData("Project 2026/08/19 12:41:16 draft")]
    public void HumanTitles(string title) => Assert.False(ProjectTitles.IsAutoGenerated(title));

    /// <summary>The generator and its detector describe the same format.</summary>
    [Fact]
    public void TheDetectorRecognisesTheGenerator() =>
        Assert.True(ProjectTitles.IsAutoGenerated(ProjectTitles.DefaultTitle(DateTimeOffset.UtcNow, MinusFive)));
}
