// Emit the Windows brand palettes from `contract/brand.json`.
//
//   node scripts/gen-brand.mjs            # write the file
//   node scripts/gen-brand.mjs --check    # fail if it is stale (what CI runs)
//
// `contract/brand.json` is THE brand contract and is byte-identical to the copy
// in Armadillon44/shotAI_MacOS, which generates its own palette from it with
// Scripts/gen-brand.swift. Every drift found in the 2026-09-14 cross-check was a
// single value edited on one side and not the other; a table generated from one
// file cannot drift that way.
//
// Node builtins only — no dependency, so it runs after `npm ci --ignore-scripts`.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specPath = path.join(root, 'contract/brand.json');
const outPath = path.join(root, 'src/shared/brand-colors.generated.ts');
const check = process.argv.includes('--check');

const die = (m) => {
  process.stderr.write(`gen-brand: ${m}\n`);
  process.exit(1);
};

const specBytes = readFileSync(specPath);
// Hash the CANONICAL bytes, not whatever the worktree holds. A default Windows
// clone (core.autocrlf=true) rewrites this file to CRLF on checkout, which
// changes the digest and makes the stamp disagree with the macOS copy — the one
// disagreement the stamp exists to reveal. .gitattributes now pins the file to
// LF, and this makes the script correct even in a tree that predates it.
const canonicalSpec = Buffer.from(specBytes.toString('utf8').replace(/\r\n/g, '\n'), 'utf8');
// The contract's content hash, stamped into the generated header. The same file
// lives in Armadillon44/shotAI_MacOS and its generated table carries the same
// line, so "both repos hold the same contract" is checkable by eye rather than
// asserted in prose.
const specHash = createHash('sha256').update(canonicalSpec).digest('hex');
const spec = JSON.parse(specBytes.toString('utf8'));
const { brands, windowsRenames: RENAME = {}, platforms } = spec;
const tokens = platforms?.windows?.colors ?? die('spec has no platforms.windows.colors');

/** `6`, or `{macos, windows}` for a value the platforms have not agreed on. */
const platformValue = (v) => (v && typeof v === 'object' && !Array.isArray(v) ? v.windows : v);

const hex = (s, where) => {
  if (typeof s !== 'string' || !/^#[0-9a-f]{6}$/.test(s)) {
    die(`${where}: expected a lowercase 6-digit #rrggbb, got ${JSON.stringify(s)}`);
  }
  return s;
};

// Invariants, checked at GENERATION time so a palette that breaks one cannot be
// committed. The dark-field rule below is the one this repo shipped broken:
// fieldBg was exactly surface2, so a text field on an elevated card did not read
// as an input. A rule, not a one-off fix.
for (const inv of spec.invariants ?? []) {
  if (inv.rule !== 'distinct' || inv.tokens?.length !== 2) continue;
  for (const [bname, b] of Object.entries(brands)) {
    const [x, y] = inv.tokens.map((t) => b.colors?.[t]?.[inv.mode]);
    if (x && y && x === y) {
      die(`invariant violated — ${bname}.${inv.mode}: ${inv.tokens.join(' and ')} are both ${x}.\n  ${inv.why ?? ''}`);
    }
  }
};

const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const lit = (v) => (v === null || v === undefined ? 'null' : typeof v === 'string' ? q(v) : String(v));

let out = `// GENERATED by scripts/gen-brand.mjs from contract/brand.json — DO NOT EDIT.
// contract sha256: ${specHash}
//
// Change a colour in contract/brand.json and regenerate; the same file drives
// Packages/ShotModel/Sources/ShotModel/BrandPalette+Generated.swift in
// Armadillon44/shotAI_MacOS, so the two platforms cannot disagree about a value
// neither of them owns.
//
// The types, the helpers and everything about how these are CONSUMED live in
// theme-palette.ts, by hand. Only the table is generated.
import type { Brand, BrandId } from './theme-palette';

export const BRANDS: Record<BrandId, Brand> = {
`;

for (const bname of ['shotAI', 'lfi']) {
  const b = brands[bname] ?? die(`brand ${bname} missing from the contract`);
  const mode = (m) =>
    tokens
      .map((t) => {
        const c = b.colors?.[t] ?? die(`${bname}: no colour "${t}" in the contract`);
        return `      ${RENAME[t] ?? t}: ${q(hex(c[m], `${bname}.${t}.${m}`))},`;
      })
      .join('\n');
  const r = b.radii ?? die(`${bname}: no radii`);
  const f = b.font ?? die(`${bname}: no font`);
  out += `  ${bname}: {
    label: ${q(b.label)},
    radii: { ${['panel', 'card', 'figure', 'control', 'controlSm', 'micro', 'chip']
      .map((k) => `${k}: ${lit(platformValue(r[k]))}`)
      .join(', ')} },
    font: {
      family: ${lit(f.family)},
      fallbacks: [${(f.fallbacks ?? []).map(q).join(', ')}],
      labelStretch: ${lit(f.labelStretch)},
    },
    light: {
${mode('light')}
    },
    dark: {
${mode('dark')}
    },
  },
`;
}
out += '};\n';

if (check) {
  let existing = '';
  try {
    existing = readFileSync(outPath, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  // Compare line-ending-normalised. Without this, a CRLF worktree copy reads as
  // stale on every run, and the remedy the message prints — regenerate and
  // commit — would stamp the CRLF-derived hash and silently unpin the contract.
  const norm = (t) => t.replace(/\r\n/g, '\n');
  if (norm(existing) !== norm(out)) {
    die(`${path.basename(outPath)} is STALE.\nRun \`npm run gen:brand\` and commit the result.`);
  }
  console.log('gen-brand: up to date');
} else {
  writeFileSync(outPath, out);
  console.log(`gen-brand: wrote ${path.basename(outPath)}`);
}
